# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e4e636d8bf9363aaab40fd2636871f688d52353169001c74d9e11b3c987468a25fa2a143baf82c0f9a6ffcf57cec82b10e1ab46012cfbd4c08b56c45aeb45cb

test:
  secret_key_base: 674f926df27fd57c2970b8ca2bb458a20c7e41faeb51fc052d9d6f89170fee2680e03fa9883b9a192d513ac7a3899a7ef30f54085a59bf1f80df9a343126a4ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
